const RUTA_SUBIDAS  = './subidas/';
const IMAGEN_NO_ENCONTRADA = './subidas/imagen_not_found.jpg';

const ESQUEMA_BD = 'pasico_gestor';
const ESQUEMA_BD_WEB = 'pasico';
const ROL_ADMINISTRADOR = 1;

const TIPO_PERSONA_MUSICO = 1;
const TIPO_PERSONA_ALUMNO = 2;
const TIPO_PERSONA_PADRE = 3;

const ASIGNATURA_LENGUAJE = 0;
const ASIGNATURA_INSTRUMENTO_BANDA = 1;
const ASIGNATURA_INSTRUMENTO_NO_BANDA = 2;
const ASIGNATURA_BANDA = 3;

module.exports.RUTA_SUBIDAS = RUTA_SUBIDAS;
module.exports.IMAGEN_NO_ENCONTRADA = IMAGEN_NO_ENCONTRADA;

module.exports.ESQUEMA_BD = ESQUEMA_BD;
module.exports.ESQUEMA_BD_WEB = ESQUEMA_BD_WEB;
module.exports.ROL_ADMINISTRADOR = ROL_ADMINISTRADOR;

module.exports.TIPO_PERSONA_MUSICO = TIPO_PERSONA_MUSICO;
module.exports.TIPO_PERSONA_ALUMNO = TIPO_PERSONA_ALUMNO;
module.exports.TIPO_PERSONA_PADRE = TIPO_PERSONA_PADRE;

module.exports.ASIGNATURA_LENGUAJE = ASIGNATURA_LENGUAJE;
module.exports.ASIGNATURA_INSTRUMENTO_BANDA = ASIGNATURA_INSTRUMENTO_BANDA;
module.exports.ASIGNATURA_INSTRUMENTO_NO_BANDA = ASIGNATURA_INSTRUMENTO_NO_BANDA;
module.exports.ASIGNATURA_BANDA = ASIGNATURA_BANDA;