const RUTA_SUBIDAS  = './subidas/';
const IMAGEN_NO_ENCONTRADA = './subidas/imagen_not_found.jpg';

const ESQUEMA_BD = 'pasico';
const ROL_ADMINISTRADOR = 1;

const TIPO_COMPONENTE_TEXTO = 1;
const TIPO_COMPONENTE_IMAGEN = 2;
const TIPO_COMPONENTE_COMPONENTES = 3;
const TIPO_COMPONENTE_VIDEO = 4;
const TIPO_COMPONENTE_GALERIA = 5;
const TIPO_COMPONENTE_PAGINAS = 6;
const TIPO_COMPONENTE_CARUSEL = 7;

const TIPO_ASOCIACION_PAGINA = 1;
const TIPO_ASOCIACION_COMPONENTE = 2;

const TIPO_PAGINA_GENERAL = 1;

module.exports.RUTA_SUBIDAS = RUTA_SUBIDAS;
module.exports.IMAGEN_NO_ENCONTRADA = IMAGEN_NO_ENCONTRADA;

module.exports.ESQUEMA_BD = ESQUEMA_BD;
module.exports.ROL_ADMINISTRADOR = ROL_ADMINISTRADOR;

module.exports.TIPO_COMPONENTE_TEXTO = TIPO_COMPONENTE_TEXTO;
module.exports.TIPO_COMPONENTE_IMAGEN = TIPO_COMPONENTE_IMAGEN;
module.exports.TIPO_COMPONENTE_COMPONENTES = TIPO_COMPONENTE_COMPONENTES;
module.exports.TIPO_COMPONENTE_VIDEO = TIPO_COMPONENTE_VIDEO;
module.exports.TIPO_COMPONENTE_GALERIA = TIPO_COMPONENTE_GALERIA;
module.exports.TIPO_COMPONENTE_PAGINAS = TIPO_COMPONENTE_PAGINAS;
module.exports.TIPO_COMPONENTE_CARUSEL = TIPO_COMPONENTE_CARUSEL;

module.exports.TIPO_ASOCIACION_COMPONENTE = TIPO_ASOCIACION_COMPONENTE;
module.exports.TIPO_ASOCIACION_PAGINA = TIPO_ASOCIACION_PAGINA;

module.exports.TIPO_PAGINA_GENERAL = TIPO_PAGINA_GENERAL;